# Generated by Django 4.2.6 on 2023-10-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontacts',
            name='address',
            field=models.CharField(default='856 Cordia Extension Apt. 356, Lake, United State', max_length=100, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
