# Generated by Django 4.2.6 on 2023-10-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_rooms_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sum',
        ),
        migrations.AddField(
            model_name='rooms',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('occupied', 'occupied'), ('not_available', 'not available')], default='available', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='info',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='services',
            field=models.TextField(null=True, verbose_name='сервисы'),
        ),
    ]
