# Generated by Django 4.2.6 on 2023-10-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_booking_options_remove_booking_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_details', models.ImageField(upload_to='media')),
                ('content', models.CharField(max_length=300, null=True, verbose_name='контент')),
            ],
        ),
    ]
