# Generated by Django 4.2.6 on 2023-10-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_rename_blog_details_blog_details_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Details',
        ),
    ]
