# Generated by Django 4.2.6 on 2023-10-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_commentroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentroom',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
