# Generated by Django 4.2.6 on 2023-10-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_commentroom_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentroom',
            options={'verbose_name': 'Коментария комнаты', 'verbose_name_plural': 'Коментария комнаты'},
        ),
    ]
